export const TEAM_LIST = [
  '강원',
  '광주',
  '김천',
  '대구',
  '대전',
  '제주',
  '서울',
  '수원FC',
  '안양',
  '울산',
  '전북',
  '포항',
  '경남',
  '김포',
  '부산',
  '부천',
  '서울E',
  '성남',
  '수원',
  '안산',
  '인천',
  '전남',
  '천안',
  '충남아산',
  '충북청주',
  '화성',
]

export const TEAM_LOGOS = {
  울산: '/Logo/ulsan.png',
  포항: '/Logo/pohang.png',
  광주: '/Logo/gwangju.png',
  전북: '/Logo/jeonbuk.png',
  대구: '/Logo/daegu.png',
  제주: '/Logo/jeju.png',
  대전: '/Logo/daejeon.png',
  수원FC: '/Logo/suwonfc.png',
  강원: '/Logo/gangwon.png',
  서울: '/Logo/seoul.png',
  김천: '/Logo/gimcheon.png',
  안양: '/Logo/anyang.png',
  경남: '/Logo/gyeongnam.png',
  김포: '/Logo/gimpo.png',
  부산: '/Logo/busan.png',
  부천: '/Logo/bucheon.png',
  서울E: '/Logo/seoul-eland.png',
  성남: '/Logo/seongnam.png',
  수원: '/Logo/suwon.png',
  안산: '/Logo/ansan.png',
  인천: '/Logo/incheon.png',
  전남: '/Logo/jeonnam.png',
  충남아산: '/Logo/chungnam-asan.png',
  충북청주: '/Logo/chungbuk-cheongju.png',
  천안: '/Logo/cheonan.png',
  화성: '/Logo/hwaseong.png',
}
